#!/bin/bash

# Update package list
sudo apt-get update

# Install required packages
sudo apt-get -y install lsb-release curl apt-transport-https

# Install packages from bookworm-backports
if sudo apt install -t bookworm-backports linux-image-amd64/bookworm-backports linux-headers-amd64/bookworm-backports firmware-linux; then
    echo "Installation successful."
else
    echo "Installation failed."
    exit 1
fi

# Update GRUB
if sudo update-grub; then
    echo "GRUB updated successfully."
else
    echo "GRUB update failed."
    exit 1
fi

# Reboot the system
echo "Rebooting the system..."
sudo reboot
