#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status

# Function to clean up
cleanup() {
    echo "Removing install.sh..."
    rm -f install.sh
}

# Trap to ensure cleanup happens on exit
trap cleanup EXIT

# Download the install script
echo "Downloading the install script..."
wget -q https://github.com/drewgrif/bookworm-scripts/raw/main/install.sh

# Make the install script executable
echo "Making install.sh executable..."
chmod +x install.sh

# Run the install script
echo "Running the install script..."
./install.sh

echo "Script finished."
